(() => {
  "use strict";
  const defs = [
    ["order", "Order", "identifier", true], ["supplier", "Supplier", "related entity", true],
    ["description", "Description", "long text", true], ["status", "Status", "category", true],
    ["amount", "Amount", "currency", true], ["neededBy", "Needed by", "date", true],
    ["region", "Region", "category", false], ["buyer", "Buyer", "related entity", false],
    ["updated", "Updated", "timestamp", false], ["notes", "Notes", "rich text", false],
    ["attachments", "Attachments", "list", false], ["sourceId", "Source ID", "unique identifier", false]
  ].map(function (d) { return { key: d[0], label: d[1], type: d[2], visible: d[3] }; });
  const suppliers = ["Northstar Components", "Morrow Industrial Supply", "Blue Heron Packaging", "Aster & Pine Logistics", "Hearthside Fabrication", "Cobalt Office Systems", "Juniper Field Services", "Lumen Circuit Works"];
  const regions = ["North", "South", "East", "West", "Central"];
  const buyers = ["Maya Chen", "Jon Bell", "Priya Shah", "Owen Wright", "Nia Brooks", "Tess Morgan"];
  const statuses = ["On track", "At risk", "Blocked", "Complete"];
  const parts = ["replacement control panels", "temperature-safe packing kits", "warehouse scanning hardware", "quarterly safety inspection", "custom anodized brackets", "regional freight capacity", "network access points", "field calibration service"];
  const notes = [null, "Supplier confirmed the revised ship window.", "Awaiting receiving team sign-off.", null, "Original quote had a missing tax code.", "Escalated to the regional buyer."];
  const files = [[], ["quote.pdf"], ["quote.pdf", "spec-sheet.pdf"], ["invoice.pdf", "delivery-photo.jpg", "packing-list.pdf"]];
  const state = { rows: [], fields: defs.map(function (f) { return Object.assign({}, f); }), search: "", status: new Set(), region: new Set(), min: "", max: "", sort: "order", direction: "default", page: 1, size: 30, views: {}, modified: false, focus: null, focusOrder: null, selectedOrder: null, openFilters: new Set(), railFocus: null, saveFocus: null };
  function $(id) { return document.getElementById(id); }
  const el = { search: $("global-search"), sort: $("sort-field"), direction: $("sort-direction"), view: $("view-select"), demo: $("demo-state"), saveState: $("save-state"), explore: $("explore-toggle"), hidden: $("hidden-count"), save: $("save-view"), summary: $("result-summary"), visible: $("visible-summary"), filters: $("active-filters"), reset: $("reset-all"), rail: $("field-rail"), railClose: $("rail-close"), fieldList: $("field-list"), head: $("table-head"), body: $("table-body"), panel: document.querySelector(".table-panel"), empty: $("empty-state"), emptyCopy: $("empty-copy"), pageSummary: $("page-summary"), pageNumber: $("page-number"), prev: $("prev-page"), next: $("next-page"), resetEmpty: $("reset-empty"), inspector: $("inspector"), scrim: $("scrim"), close: $("inspector-close"), inspectorTitle: $("inspector-title"), context: $("inspector-context"), detail: $("detail-grid"), saveScrim: $("save-scrim"), saveDialog: $("save-dialog"), saveForm: $("save-form"), viewName: $("view-name"), viewNameError: $("view-name-error"), saveCancel: $("save-cancel"), saveConfirm: $("save-confirm"), toast: $("toast"), responsive: $("responsive-fields") };
  function rng(seed) { let x = seed >>> 0; return function () { x = (x * 1664525 + 1013904223) >>> 0; return x / 4294967296; }; }
  function makeRows(count) {
    const random = rng(20260818);
    return Array.from({ length: count }, function (_, i) {
      const n = i + 1, amount = Math.round((1250 + random() * 183250) / 50) * 50;
      const supplier = suppliers[(i * 3 + Math.floor(random() * suppliers.length)) % suppliers.length];
      const needed = new Date(Date.UTC(2026, 5, 15 + ((i * 11) % 170)));
      const updated = new Date(Date.UTC(2026, 6, 1 + ((i * 5) % 48), 8 + (i % 8), (i * 13) % 60));
      return {
        order: "PO-" + n, supplier: supplier,
        description: parts[i % parts.length] + " for " + supplier.toLowerCase() + (n % 5 === 0 ? " with a revised delivery window and serialized receiving checks." : " for the spring intake."),
        status: statuses[(i * 7 + Math.floor(random() * statuses.length)) % statuses.length], amount: amount,
        neededBy: n === 37 ? "2026-99-14" : needed.toISOString().slice(0, 10),
        region: regions[(i * 3 + 1) % regions.length], buyer: buyers[(i * 2 + Math.floor(random() * buyers.length)) % buyers.length],
        updated: updated.toISOString(), notes: notes[i % notes.length], attachments: files[(i + (amount > 160000 ? 2 : 0)) % files.length],
        sourceId: "SRC-" + String(700000 + n * 17).padStart(6, "0")
      };
    });
  }
  state.rows = makeRows(1000);
  function esc(value) { return String(value == null ? "" : value).replace(/[&<>\"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]; }); }
  function money(value) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
  function date(value) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return value ? "Malformed: " + value : "Not set"; const d = new Date(value + "T00:00:00Z"); return Number.isNaN(d.getTime()) ? "Malformed: " + value : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(d); }
  function timestamp(value) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
  function field(key) { return state.fields.find(function (f) { return f.key === key; }); }
  function visibleFields() { return state.fields.filter(function (f) { return f.visible; }); }
  function value(f, row) { const v = row[f.key]; if (f.key === "amount") return money(v); if (f.key === "neededBy") return date(v); if (f.key === "updated") return timestamp(v); if (f.key === "attachments") return v.length ? v.length + " file" + (v.length === 1 ? "" : "s") : "None"; return v == null ? "" : v; }
  function matches(row) { const q = state.search.trim().toLowerCase(); return q ? state.fields.filter(function (f) { return String(value(f, row)).toLowerCase().includes(q); }).map(function (f) { return f.key; }) : []; }
  function rows() {
    const q = state.search.trim().toLowerCase();
    const result = state.rows.filter(function (r) { return (!q || state.fields.some(function (f) { return String(value(f, r)).toLowerCase().includes(q); })) && (!state.status.size || state.status.has(r.status)) && (!state.region.size || state.region.has(r.region)) && (!state.min || r.amount >= Number(state.min)) && (!state.max || r.amount <= Number(state.max)); });
    if (state.direction === "default") return result;
    const f = field(state.sort), dir = state.direction === "asc" ? 1 : -1;
    return result.sort(function (a, b) { let av = a[f.key], bv = b[f.key]; if (f.key === "order" || f.key === "sourceId") { av = Number(String(av).match(/\d+/)[0]); bv = Number(String(bv).match(/\d+/)[0]); } else if (f.key === "amount") { av = Number(av); bv = Number(bv); } return (typeof av === "number" ? av - bv : String(av == null ? "" : av).localeCompare(String(bv == null ? "" : bv))) * dir; });
  }
  function display(f, row) { const v = row[f.key]; const hidden = matches(row).includes(f.key) && !f.visible ? '<span class="match-note">Search match: ' + f.label + "</span>" : ""; const attr = 'class="row-action" type="button" data-row="' + row.order + '"'; if (f.key === "status") return "<td><button " + attr + '><span class="status status-' + v.toLowerCase().replaceAll(" ", "-") + '">' + esc(v) + "</span>" + hidden + "</button></td>"; const classes = (f.key === "amount" ? "numeric amount " : "") + (f.key === "neededBy" ? "date-cell " : "") + (v == null ? "muted-cell" : ""); return '<td class="' + classes + '"><button ' + attr + ">" + esc(value(f, row) || "Not set") + hidden + "</button></td>"; }
  function renderHead() { el.head.innerHTML = "<tr>" + visibleFields().map(function (f) { const current = state.sort === f.key ? state.direction : "default"; const ariaSort = current === "asc" ? "ascending" : current === "desc" ? "descending" : "none"; const next = current === "default" ? "ascending" : current === "asc" ? "descending" : "default order"; const marker = current !== "default" ? '<span class="sort-marker" aria-hidden="true">' + (current === "asc" ? "↑" : "↓") + "</span>" : ""; return '<th scope="col" aria-sort="' + ariaSort + '" class="' + (f.key === "amount" ? "numeric" : "") + '"><button type="button" data-sort="' + f.key + '" aria-label="Sort by ' + f.label + '; currently ' + (current === "default" ? "default order" : current) + '. Activate for ' + next + '.">' + f.label + " " + marker + "</button></th>"; }).join("") + "</tr>"; }
  function renderBody(list) { const pages = Math.max(1, Math.ceil(list.length / state.size)); state.page = Math.min(state.page, pages); const start = (state.page - 1) * state.size, pageRows = list.slice(start, start + state.size); el.body.innerHTML = pageRows.map(function (r) { const hiddenMatch = matches(r).filter(function (k) { return !field(k).visible; }).map(function (k) { return field(k).label; }); const selected = state.selectedOrder === r.order; return '<tr id="row-' + r.order + '" aria-selected="' + selected + '" class="' + (selected ? "is-selected" : "") + '">' + visibleFields().map(function (f) { return f.key === "order" ? '<td><button class="order-link row-action" type="button" data-row="' + r.order + '">' + esc(r.order) + (hiddenMatch.length ? '<span class="match-note">Search match: ' + esc(hiddenMatch.join(", ")) + "</span>" : "") + "</button></td>" : f.key === "description" ? '<td><button class="row-action description" type="button" data-row="' + r.order + '">' + esc(r.description) + "</button></td>" : display(f, r); }).join("") + "</tr>"; }).join(""); el.empty.hidden = Boolean(list.length); el.panel.querySelector("table").hidden = !list.length; el.pageSummary.textContent = list.length ? "Rows " + (start + 1) + "–" + Math.min(start + state.size, list.length) + " of " + list.length.toLocaleString() : "0 matching rows"; el.pageNumber.textContent = "Page " + state.page + " of " + pages; el.prev.disabled = state.page <= 1; el.next.disabled = state.page >= pages; el.visible.textContent = list.length ? "Showing " + pageRows.length + " rows on this page" : "No rows on this page"; }
  function filterActive(key) { return key === "status" ? state.status.size > 0 : key === "region" ? state.region.size > 0 : Boolean(state.min || state.max); }
  function amountHistogram() { const amounts = state.rows.map(function (r) { return r.amount; }), min = Math.min.apply(null, amounts), max = Math.max.apply(null, amounts), bins = Array(6).fill(0), step = (max - min) / bins.length; amounts.forEach(function (amount) { bins[Math.min(bins.length - 1, Math.floor((amount - min) / step))]++; }); const peak = Math.max.apply(null, bins); return '<div class="amount-distribution" role="img" aria-label="Amount distribution across six value bands">' + bins.map(function (count) { return '<span class="histogram-bar" style="height:' + Math.max(8, Math.round(count / peak * 100)) + '%"></span>'; }).join("") + '</div><p class="histogram-caption">' + money(min) + "–" + money(max) + " · six value bands</p>"; }
  function filterMarkup(f) { if (f.key === "status" || f.key === "region") { const values = f.key === "status" ? statuses : regions, active = f.key === "status" ? state.status : state.region; return '<div class="category-options">' + values.map(function (v) { return '<label><input type="checkbox" data-category="' + f.key + '" value="' + v + '"' + (active.has(v) ? " checked" : "") + " />" + v + "</label>"; }).join("") + "</div>"; } return '<div class="range-controls"><input type="number" min="0" step="50" placeholder="Min $" aria-label="Minimum amount" data-amount="min" value="' + esc(state.min) + '" /><input type="number" min="0" step="50" placeholder="Max $" aria-label="Maximum amount" data-amount="max" value="' + esc(state.max) + '" /></div>' + amountHistogram(); }
  function renderRail() { const hidden = state.fields.filter(function (f) { return !f.visible; }), shown = visibleFields(), filterable = ["status", "region", "amount"]; el.fieldList.innerHTML = state.fields.map(function (f, i) { const nulls = state.rows.filter(function (r) { return r[f.key] == null || r[f.key] === ""; }).length, signal = f.key === "sourceId" ? "1,000 unique values" : nulls ? Math.round(nulls / state.rows.length * 100) + "% empty" : "Sample: " + esc(value(f, state.rows[0])), isFilterable = filterable.includes(f.key), open = isFilterable && (state.openFilters.has(f.key) || filterActive(f.key)); const filterButton = isFilterable ? '<button class="field-filter-toggle" type="button" data-filter-toggle="' + f.key + '" aria-expanded="' + open + '" aria-controls="filter-' + f.key + '">' + (open ? "Hide filter" : "Filter") + (filterActive(f.key) ? " · active" : "") + "</button>" : ""; return '<div class="field-item ' + (f.visible ? "" : "is-hidden") + (open ? " filter-open" : "") + '" data-field-item="' + f.key + '"><div class="field-top"><label class="field-check"><input type="checkbox" data-visibility="' + f.key + '"' + (f.visible ? " checked" : "") + ' /><span><span class="field-name">' + f.label + '</span><span class="field-type">' + f.type + '</span></span></label><div class="field-actions"><button type="button" data-move="up" data-field="' + f.key + '" aria-label="Move ' + f.label + ' up"' + (i ? "" : " disabled") + '>↑</button><button type="button" data-move="down" data-field="' + f.key + '" aria-label="Move ' + f.label + ' down"' + (i === state.fields.length - 1 ? " disabled" : "") + '>↓</button></div></div><div class="field-meta">' + signal + (f.key === "notes" ? " · includes nulls" : "") + "</div>" + filterButton + (isFilterable ? '<div class="field-filter" id="filter-' + f.key + '">' + filterMarkup(f) + "</div>" : "") + "</div>"; }).join(""); el.hidden.textContent = hidden.length + " hidden"; el.responsive.textContent = "Configured hidden: " + (hidden.length ? hidden.map(function (f) { return f.label; }).join(", ") : "none") + ". Shown fields: " + shown.map(function (f) { return f.label; }).join(", ") + " (may be off-screen on narrow widths; scroll horizontally)."; }
  function chip(label, text, remove) { const id = "remove-" + Math.random().toString(36).slice(2); window[id] = function () { remove(); state.modified = true; render(); }; return '<span class="filter-chip">' + esc(label) + ": " + esc(text) + ' <button type="button" aria-label="Remove ' + esc(label) + ' filter" onclick="window.' + id + '()">×</button></span>'; }
  function renderFilters() { const list = []; if (state.search) list.push(chip("Search", state.search, function () { state.search = ""; el.search.value = ""; })); if (state.status.size) list.push(chip("Status", Array.from(state.status).join(" or "), function () { state.status.clear(); })); if (state.region.size) list.push(chip("Region", Array.from(state.region).join(" or "), function () { state.region.clear(); })); if (state.min || state.max) list.push(chip("Amount", (state.min ? money(Number(state.min)) : "$0") + "–" + (state.max ? money(Number(state.max)) : "open"), function () { state.min = ""; state.max = ""; })); el.filters.innerHTML = list.join(""); }
  function captureRailFocus() { const active = document.activeElement, item = active && active.closest ? active.closest("[data-field-item]") : null; if (!item || !el.fieldList.contains(item)) return null; return { field: item.dataset.fieldItem, kind: active.dataset.visibility ? "visibility" : active.dataset.category ? "category" : active.dataset.amount ? "amount" : active.dataset.filterToggle ? "filterToggle" : active.dataset.move ? "move" : "", value: active.dataset.move ? active.dataset.field : active.dataset.amount ? active.dataset.amount : (active.value || "") }; }
  function restoreRailFocus(focus) { if (!focus || !focus.kind) return; const item = el.fieldList.querySelector('[data-field-item="' + focus.field + '"]'); if (!item) return; const target = Array.from(item.querySelectorAll("input,button")).find(function (node) { return node.dataset[focus.kind] !== undefined && (focus.kind === "move" ? node.dataset.field === focus.value : focus.kind === "amount" ? node.dataset.amount === focus.value : (!focus.value || node.value === focus.value)); }); if (target) target.focus(); }
  function render() { const railFocus = captureRailFocus(), list = rows(); renderHead(); renderBody(list); renderRail(); renderFilters(); el.sort.innerHTML = state.fields.map(function (f) { return '<option value="' + f.key + '">' + f.label + "</option>"; }).join(""); el.sort.value = state.sort; el.direction.value = state.direction; el.summary.textContent = list.length === state.rows.length ? "1,000 orders" : list.length.toLocaleString() + " of 1,000 orders"; el.emptyCopy.textContent = state.search ? "No order matches “" + state.search + "”. Hidden fields are included in search." : "Try a shorter search or clear one of the active filters."; el.saveState.textContent = state.modified ? "Modified" : "Saved"; el.saveState.classList.toggle("modified", state.modified); restoreRailFocus(railFocus); }
  function reset() { if (!el.inspector.hidden) closeInspector(); state.search = ""; el.search.value = ""; state.status.clear(); state.region.clear(); state.min = ""; state.max = ""; state.sort = "order"; state.direction = "default"; state.page = 1; state.fields = defs.map(function (f) { return Object.assign({}, f); }); state.openFilters.clear(); state.modified = false; el.view.value = "default"; setRail(false); render(); }
  function inspect(order) { const row = state.rows.find(function (r) { return r.order === order; }); if (!row) return; state.focus = document.activeElement; state.focusOrder = order; state.selectedOrder = order; const selectedRow = document.getElementById("row-" + order); if (selectedRow) { selectedRow.setAttribute("aria-selected", "true"); selectedRow.classList.add("is-selected"); } el.inspectorTitle.textContent = order; const hidden = matches(row).filter(function (k) { return !field(k).visible; }).map(function (k) { return field(k).label; }); el.context.textContent = hidden.length ? "Opened from the current table. Search also matched hidden fields: " + hidden.join(", ") + "." : "Opened from the current table. Closing this panel keeps your filters and page."; el.detail.innerHTML = state.fields.map(function (f) { const content = f.key === "status" ? '<span class="status status-' + row.status.toLowerCase().replaceAll(" ", "-") + '">' + esc(row.status) + "</span>" : row[f.key] == null ? '<span class="muted-cell">Not set</span>' : esc(value(f, row)); return '<div class="detail-label">' + f.label + '</div><div class="detail-value ' + (["description", "notes"].includes(f.key) ? "long" : "") + '">' + content + "</div>"; }).join(""); el.scrim.hidden = false; el.inspector.hidden = false; el.inspector.setAttribute("aria-hidden", "false"); el.close.focus(); }
  function closeInspector() { const selectedRow = state.selectedOrder ? document.getElementById("row-" + state.selectedOrder) : null; if (selectedRow) { selectedRow.setAttribute("aria-selected", "false"); selectedRow.classList.remove("is-selected"); } el.scrim.hidden = true; el.inspector.hidden = true; el.inspector.setAttribute("aria-hidden", "true"); const fallback = state.focus && document.body.contains(state.focus) ? state.focus : (state.focusOrder && el.body.querySelector('[data-row="' + state.focusOrder + '"]')) || el.body.querySelector("[data-row]") || el.explore; if (fallback) fallback.focus(); state.selectedOrder = null; state.focus = null; }
  function toast(message) { el.toast.textContent = message; el.toast.hidden = false; setTimeout(function () { el.toast.hidden = true; }, 3000); }
  function openSaveDialog() { state.saveFocus = document.activeElement; el.viewName.value = "My view " + Object.keys(state.views).length; el.viewNameError.hidden = true; el.saveScrim.hidden = false; el.saveDialog.hidden = false; el.saveDialog.setAttribute("aria-hidden", "false"); el.viewName.focus(); el.viewName.select(); }
  function closeSaveDialog() { el.saveScrim.hidden = true; el.saveDialog.hidden = true; el.saveDialog.setAttribute("aria-hidden", "true"); const fallback = state.saveFocus && document.body.contains(state.saveFocus) ? state.saveFocus : el.save; if (fallback) fallback.focus(); state.saveFocus = null; }
  function saveView() { const label = el.viewName.value.trim(); if (!label) { el.viewNameError.hidden = false; el.viewName.focus(); return; } const id = "view-" + Date.now(); state.views[id] = { label: label, search: state.search, fields: state.fields.map(function (f) { return { key: f.key, visible: f.visible }; }), sort: state.sort, direction: state.direction, status: Array.from(state.status), region: Array.from(state.region), min: state.min, max: state.max }; const option = document.createElement("option"); option.value = id; option.textContent = label; el.view.append(option); el.view.value = id; state.modified = false; render(); closeSaveDialog(); toast("Saved “" + label + "” locally."); }
  function restoreView(id) { if (id === "default") { reset(); return; } const view = state.views[id]; if (!view) return; state.search = view.search || ""; el.search.value = state.search; state.fields = view.fields.map(function (saved) { const original = defs.find(function (f) { return f.key === saved.key; }); return original ? Object.assign({}, original, { visible: saved.visible }) : null; }).filter(Boolean); state.sort = view.sort; state.direction = view.direction; state.status = new Set(view.status); state.region = new Set(view.region); state.min = view.min; state.max = view.max; state.page = 1; state.openFilters = new Set(["status", "region", "amount"].filter(function (key) { return (key === "status" && state.status.size) || (key === "region" && state.region.size) || (key === "amount" && (state.min || state.max)); })); state.modified = false; render(); }
  function setRail(open) { el.rail.hidden = !open; el.explore.setAttribute("aria-expanded", String(open)); }
  function applyDemo(name, writeHash) { const demo = name || "default"; reset(); if (demo === "filtered") { state.status = new Set(["At risk", "Blocked"]); state.min = "25000"; state.max = "100000"; state.openFilters = new Set(["status", "amount"]); state.modified = true; render(); } else if (demo === "rail") { setRail(true); state.openFilters = new Set(["amount"]); render(); } else if (demo === "quality") { inspect("PO-37"); } else if (demo === "empty") { state.search = "no-such-order"; el.search.value = state.search; state.modified = true; render(); } else if (demo === "modified") { const region = field("region"); region.visible = true; const amountIndex = state.fields.findIndex(function (f) { return f.key === "amount"; }), amount = state.fields.splice(amountIndex, 1)[0]; state.fields.splice(1, 0, amount); state.modified = true; render(); } if (el.demo) el.demo.value = demo; if (writeHash && typeof location !== "undefined") location.hash = "demo=" + encodeURIComponent(demo); }
  function demoFromHash() { if (typeof location === "undefined") return ""; const match = location.hash.match(/^#demo=([^&]+)/); return match ? decodeURIComponent(match[1]) : ""; }

  el.search.addEventListener("input", function () { state.search = el.search.value; state.page = 1; state.modified = true; render(); });
  el.save.addEventListener("click", openSaveDialog); el.saveForm.addEventListener("submit", function (event) { event.preventDefault(); saveView(); }); el.saveCancel.addEventListener("click", closeSaveDialog); el.saveScrim.addEventListener("click", closeSaveDialog); el.view.addEventListener("change", function () { restoreView(el.view.value); });
  el.demo.addEventListener("change", function () { applyDemo(el.demo.value, true); });
  el.sort.addEventListener("change", function () { state.sort = el.sort.value; if (state.direction === "default") state.direction = "asc"; state.modified = true; render(); });
  el.direction.addEventListener("change", function () { state.direction = el.direction.value; state.modified = true; render(); });
  el.explore.addEventListener("click", function () { const show = el.rail.hidden; el.rail.hidden = !show; el.explore.setAttribute("aria-expanded", String(show)); if (show) el.railClose.focus(); });
  el.railClose.addEventListener("click", function () { el.rail.hidden = true; el.explore.setAttribute("aria-expanded", "false"); el.explore.focus(); });
  el.reset.addEventListener("click", reset); el.resetEmpty.addEventListener("click", reset); el.prev.addEventListener("click", function () { state.page--; render(); }); el.next.addEventListener("click", function () { state.page++; render(); }); el.close.addEventListener("click", closeInspector); el.scrim.addEventListener("click", closeInspector);
  function trapDialog(container, event) { const focusable = Array.from(container.querySelectorAll("button,input,select,textarea,a[href],[tabindex]:not([tabindex='-1'])")).filter(function (node) { return !node.disabled; }); if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }
  document.addEventListener("keydown", function (event) { if (event.key === "/" && !["INPUT", "SELECT"].includes(document.activeElement.tagName)) { event.preventDefault(); el.search.focus(); } if (!el.saveDialog.hidden) { if (event.key === "Escape") { event.preventDefault(); closeSaveDialog(); } else if (event.key === "Tab") trapDialog(el.saveDialog, event); return; } if (event.key === "Escape" && !el.inspector.hidden) { event.preventDefault(); closeInspector(); } if (event.key === "Tab" && !el.inspector.hidden) trapDialog(el.inspector, event); });
  el.head.addEventListener("click", function (event) { const b = event.target.closest("[data-sort]"); if (!b) return; if (state.sort !== b.dataset.sort) { state.sort = b.dataset.sort; state.direction = "asc"; } else if (state.direction === "default") state.direction = "asc"; else if (state.direction === "asc") state.direction = "desc"; else state.direction = "default"; state.page = 1; state.modified = true; render(); });
  el.body.addEventListener("click", function (event) { const b = event.target.closest("[data-row]"); if (b) inspect(b.dataset.row); });
  el.fieldList.addEventListener("input", function (event) { const t = event.target; if (!t.dataset.amount) return; if (t.dataset.amount === "min") state.min = t.value; else state.max = t.value; state.page = 1; state.modified = true; render(); });
  el.fieldList.addEventListener("change", function (event) { const t = event.target; if (t.dataset.visibility) { field(t.dataset.visibility).visible = t.checked; state.modified = true; render(); } if (t.dataset.category) { const set = t.dataset.category === "status" ? state.status : state.region; t.checked ? set.add(t.value) : set.delete(t.value); state.page = 1; state.modified = true; render(); } if (t.dataset.amount) { if (t.dataset.amount === "min") state.min = t.value; else state.max = t.value; state.page = 1; state.modified = true; render(); } });
  el.fieldList.addEventListener("click", function (event) { const filterButton = event.target.closest("[data-filter-toggle]"); if (filterButton) { const key = filterButton.dataset.filterToggle; if (state.openFilters.has(key)) state.openFilters.delete(key); else state.openFilters.add(key); render(); return; } const b = event.target.closest("[data-move]"); if (!b) return; const i = state.fields.findIndex(function (f) { return f.key === b.dataset.field; }), j = b.dataset.move === "up" ? i - 1 : i + 1; if (j < 0 || j >= state.fields.length) return; [state.fields[i], state.fields[j]] = [state.fields[j], state.fields[i]]; state.modified = true; render(); });
  const initialDemo = demoFromHash(); if (initialDemo) applyDemo(initialDemo, false); else render();
})(); 
